# Naming and Tagging Vars
location         = "centralus"
 subnet_id = "/subscriptions/208d9d5e-b1ba-42e2-9dcf-a3ac58050bc9/resourceGroups/zcmrgnetp02/providers/Microsoft.Network/virtualNetworks/zcmvnnetp02/subnets/PaaSApp-Integration-Net"
 lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
# # App Config Vars
 appservice_plan_name                = "zenccsapsdr01"
 appservice_plan_resource_group_name = "ZCCSRGDR"
resource_group_name =  "ZCCSRGDR"
workspace_id = "/subscriptions/208d9d5e-b1ba-42e2-9dcf-a3ac58050bc9/resourceGroups/zccsrgdr/providers/Microsoft.OperationalInsights/workspaces/zenccslawsdr01"
env ="prod"
# # Data Vars
#azuread_administrator_group_name = "Zelis DBA Group"
tags = {
location = "centralus"
environment = "dr"
app-name = "PRIZM"
cost-center = ""
organizational-owner = "CCS"
application-owner = "CCS-DevOps@zelis.com"
engineering-owner = "dl-azure_support@zelis.com"
deployment-date = "05/23/2023"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
 }
db_enabled = "true"
shared_key_vault_name = "ZENINFKVDR01"
shared_key_vault_resource_group_name = "ZENEETDRRGP"
wildcard_cert_name = "ExternalAppSvcZelisWC"
custom_domain_verification_id = "20.84.141.2"
zone_name = "zelis.com"
application_name = "zccseapiwadr01"
record_type = "A"
cert_enabled = "true"