location         = "centralus"
resource_group_name = "zcmssrgdr"
application_name = "zcmoonaawadr01"
api_application_name = "zcmoonaaapiwadr01"
virtual_network_name = "zcmvnnetp02"
virtual_network_resource_group_name="zcmrgnetp02"
storage_account_name = "zcmoonaastrdr01"
account_replication_type ="GRS"
subnet_id = "/subscriptions/208d9d5e-b1ba-42e2-9dcf-a3ac58050bc9/resourceGroups/zcmrgnetp02/providers/Microsoft.Network/virtualNetworks/zcmvnnetp02/subnets/PaaSApp-Integration-Net-3"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
app_insights_name = "zcmoonaaaidr01"
workspace_id = "/subscriptions/208d9d5e-b1ba-42e2-9dcf-a3ac58050bc9/resourceGroups/zcmssrgdr/providers/Microsoft.OperationalInsights/workspaces/zcmssladr01"
env = "prod"
 appservice_plan_name                = "zcmssapsdr01"
 appservice_plan_resource_group_name = "zcmssrgdr"
 cert_enabled = "false"
shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
zone_name = "zelis.com"
record_type = "CNAME"
  tags= {
        Product= "OONAuditApp",
        business-unit= "PRICEOPTIMIZATION",
        compliance-framework= "HIPAA",
        application-owner= "CCS-DevOps@zelis.com",
        engineering-owner   = "dl-azure_support@zelis.com",
        environment-stage   = "production"
    }