
location         = "eastus2"
resource_group_name = "zenrpargd01"
subnet_id = "/subscriptions/a83e8185-1a93-47ea-b589-273f5cf62d49/resourceGroups/zenpargnetd01/providers/Microsoft.Network/virtualNetworks/zenpavnnetd01/subnets/PaaSApp-Integration-Net-Dev"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
appservice_plan_name                = "zenrpaaspd03"
appservice_plan_resource_group_name = "zenrpargd01"
env = "nonprod"
tags = {
      
location = "us-east2"
environment = "dev"
app-name = ""
cost-center = ""
organizational-owner = "RPA"
application-owner = "RPA@zelis.com"
engineering-owner = "dl-azure_support@zelis.com"
deployment-date = "07/18/2023"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
    }
db_enabled = "true"


cert_enabled = "true"
shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
#custom_domain_verification_id = "20.22.102.82"
zone_name = "zelis.com"
#application_name = "zcmrbpptnaau01"
record_type = "CNAME"
