
location         = "eastus2"
resource_group_name = "ZENSOPSRGD"
subnet_id = "/subscriptions/8cd6f7a7-7407-423c-9896-98900c199a19/resourceGroups/zensorgnetp01/providers/Microsoft.Network/virtualNetworks/zensovnnetp01/subnets/SecOps-Infrastructure"
#lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
#lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust" 
appservice_plan_name                = "ZENPEEAASPD01"
appservice_plan_resource_group_name = "ZENPEEARGD"
env ="nonprod"
account_replication_type = "ZRS"
tags = {     
location = "us-east2"
environment = "dev"
app-name = "SecOps"
cost-center = ""
organizational-owner = "SecOps"
application-owner = "Zelis-ITSecurityOperationsAllAssociates@zelis.com"
engineering-owner = "dl-azure_support@zelis.com"
deployment-date = "09/05/2024"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
    }
db_enabled = "true"
cert_enabled = "false"

shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"

custom_domain_verification_id = "zenaxlixfad01.azurewebsites.net"
zone_name = "zelis.com"
application_name = "zenaxlixfad01"
record_type = "CNAME"

