
location         = "eastus2"
resource_group_name = "ZENZADARGP"
subnet_id = "/subscriptions/d4b3a18f-3efa-468e-8f52-0defd34c17bd/resourceGroups/zenpergnetp01/providers/Microsoft.Network/virtualNetworks/zenpevnnetp01/subnets/PaaSApp-Integration-Net-PRD"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
appservice_plan_name                = "ZENPEEAASPP01"
appservice_plan_resource_group_name = "ZENZADARGP"
 azuread_administrator_group_name = "Zelis DBA Group"
tags = {
      
location = "us-east2"
environment = "prd"
app-name = ""
cost-center = ""
organizational-owner = "ZADA"
application-owner = "ZeDWSupport@zelis.com"
engineering-owner = "dl-azure_support@zelis.com"
deployment-date = "05/25/2023"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
    }
db_enabled = "true"


shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
custom_domain_verification_id = "20.22.102.76"
zone_name = "zelis.com"
application_name = "zenjapifap01"
record_type = "A"
