location         = "eastus2"
resource_group_name = "zcmssrgu"
application_name = "zcmiassutwau01"
virtual_network_name = "zcmvnnetdev01"
virtual_network_resource_group_name="zcmrgnetdev01"
storage_account_name = "zcmssstru01"
storage_account_id = "/subscriptions/28d5fce1-5074-44b5-b372-6738d84565aa/resourceGroups/zcmssrgu/providers/Microsoft.Storage/storageAccounts/zcmssstru01"
subnet_id = "/subscriptions/28d5fce1-5074-44b5-b372-6738d84565aa/resourceGroups/zcmrgnetd01/providers/Microsoft.Network/virtualNetworks/zcmvnnetd01/subnets/PaaSApp-Integration-Net-UAT-2"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
app_insights_name = "zcmssrdmaiu01"
workspace_id = "/subscriptions/28d5fce1-5074-44b5-b372-6738d84565aa/resourceGroups/zcmssrgu/providers/Microsoft.OperationalInsights/workspaces/zcmsslawu01"
env = "nonprod"
 appservice_plan_name                = "zcmssaspu01"
 appservice_plan_resource_group_name = "zcmssrgu"
 cert_enabled = "false"
shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
zone_name = "zelis.com"
record_type = "CNAME"
  tags= {
        Product= "SharedServices",
        business-unit= "PRICEOPTIMIZATION",
        compliance-framework= "HIPAA",
        application-owner= "CCS-DevOps@zelis.com",
        engineering-owner   = "dl-azure_support@zelis.com",
        environment-stage   = "non-production"
    }