
location         = "eastus2"
resource_group_name = "vindmrg"
subnet_id = "/subscriptions/f64ca80b-42ff-479f-96db-69b4e50f5703/resourceGroups/ZH-Dev-Networking/providers/Microsoft.Network/virtualNetworks/ZH-Dev-VM/subnets/Demo-subnet-2"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
appservice_plan_name                = "vinaspdm01"
appservice_plan_resource_group_name = "vintestvm"
env = "nonprod"
tags = {
      
location = "us-east2"
environment = "dev"
app-name = ""
cost-center = ""
organizational-owner = ""
application-owner = ""
engineering-owner = ""
deployment-date = "03/07/2023"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
    }
db_enabled = "true"


shared_key_vault_name = "vintestkv"
shared_key_vault_resource_group_name = "zcmpzmrg"
wildcard_cert_name = "demozelis"
custom_domain_verification_id = "vinwadm01.azurewebsites.net"
zone_name = "demo.zelis.com"
application_name = "vinwadm01"
record_type = "CNAME"
