# Naming and Tagging Vars
location         = "eastus2"
env = "prod"
resource_group_name = "ZENPEEARGP"
subnet_id = "/subscriptions/d4b3a18f-3efa-468e-8f52-0defd34c17bd/resourceGroups/zenpergnetp01/providers/Microsoft.Network/virtualNetworks/zenpevnnetp01/subnets/PaaSApp-Integration-Net-PRD"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
vnet_name = "zenpevnnetp01"
subnet_name = "PaaSApp-Integration-Net-PRD-Static"
virtual_network_resource_group_name = "zenpergnetp01"
# zone_name = "testdomain.poc"
# # App Config Vars
appservice_plan_name                = "ZENPEEAASPP01"
appservice_plan_resource_group_name = "ZENPEEARGP"
# appservice_type    = "web"


# # Data Vars
#azuread_administrator_group_name = "Zelis DBA Group"
tags = {
      
location = "us-east2"
environment = "prd"
app-name = ""
cost-center = ""
organizational-owner = "PEEA"
application-owner = "peeateam@zelis.com"
engineering-owner = "dl-azure_support@zelis.com"
deployment-date = "10/22/2022"
data-classification = "internal"
deployment-method = "IaC"
iac-repo-id = ""
latest-release-version = ""
backup-policy = ""
end-of-life = ""
operating-system = ""
project-id = ""
shutdown-schedule = "None"
    }
db_enabled = "true"
cert_enabled = "false"
azuread_administrator_group_name = "Zelis DBA Group"
shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
custom_domain_verification_id = "mimcrls.impervadns.net"
zone_name = "zelis.com"
application_name = "zeneppfap01"
record_type = "CNAME"
static_webapp_private_service_connection_name = "zeneppscp01"
static_webapp_private_endpoint_name="zeneppepsp01"
static_webapp_subresource_names = ["staticSites"]