location         = "eastus2"
resource_group_name = "zcmssrgd"
application_name = "zcmssrdmwad01"
virtual_network_name = "zcmvnnetdev01"
virtual_network_resource_group_name="zcmrgnetdev01"
storage_account_name = "zcmssstrd01"
subnet_id = "/subscriptions/730fe0fa-8321-41e7-a3a9-13d692041038/resourceGroups/zcmrgnetdev01/providers/Microsoft.Network/virtualNetworks/zcmvnnetdev01/subnets/PaaSApp-Integration-Net-Dev"
lz_subnet_id ="/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetp01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetp01/subnets/Net-Trust" 
lz_DR_subnet_id = "/subscriptions/3a07ea8c-0ac8-43d6-a21e-ed467d8ef56b/resourceGroups/zenlzrgnetdr01/providers/Microsoft.Network/virtualNetworks/zenlzvnnetdr01/subnets/Net-Trust"
app_insights_name = "zcmssrdmaid01"
workspace_id = "/subscriptions/730fe0fa-8321-41e7-a3a9-13d692041038/resourceGroups/zcmssrgd/providers/Microsoft.OperationalInsights/workspaces/zcmsslawd01"
env = "nonprod"
 appservice_plan_name                = "zcmssaspd01"
 appservice_plan_resource_group_name = "zcmssrgd"
 cert_enabled = "true"
shared_key_vault_name = "ZENINFKVP01"
shared_key_vault_resource_group_name = "ZENINFKV"
wildcard_cert_name = "ExternalAppSvcZelisWC"
zone_name = "zelis.com"
record_type = "CNAME"
  tags= {
        Product= "RDM",
        business-unit= "PRICEOPTIMIZATION",
        compliance-framework= "HIPAA",
        application-owner= ""
        engineering-owner   = "dl-azure_support@zelis.com"
        environment-stage   = "development"
    }